### ISSUE TITLE
FFMpeg not present in Ubuntu 14.10

### ISSUE THREAD

**Issue by Cqoicebordel** [ps3mediaserver/ps3mediaserver#132]
I didn't tested the last branch but only the last stable, so, sorry if it's already corrected.

I got a few errors like those when launching PMS : 

```
ERROR 2014-11-25 15:48:55.264 [pool-27-thread-2] Error initializing process: 
java.io.IOException: Cannot run program "ffmpeg": error=2, Aucun fichier ou dossier de ce type
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047) ~[na:1.7.0_65]
        at net.pms.io.ProcessWrapperImpl.run(ProcessWrapperImpl.java:183) [pms.jar:1.90.1]
        at net.pms.io.ProcessWrapperImpl.runInSameThread(ProcessWrapperImpl.java:299) [pms.jar:1.90.1]
        at net.pms.dlna.DLNAMediaInfo.getFFmpegThumbnail(DLNAMediaInfo.java:473) [pms.jar:1.90.1]
        at net.pms.dlna.DLNAMediaInfo.parse(DLNAMediaInfo.java:770) [pms.jar:1.90.1]
        at net.pms.formats.Format.parse(Format.java:269) [pms.jar:1.90.1]
        at net.pms.dlna.RealFile.resolve(RealFile.java:191) [pms.jar:1.90.1]
        at net.pms.dlna.DLNAResource.run(DLNAResource.java:837) [pms.jar:1.90.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
Caused by: java.io.IOException: error=2, Aucun fichier ou dossier de ce type
        at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.7.0_65]
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:186) ~[na:1.7.0_65]
        at java.lang.ProcessImpl.start(ProcessImpl.java:130) ~[na:1.7.0_65]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028) ~[na:1.7.0_65]
        ... 10 common frames omitted
ERROR 2014-11-25 15:48:55.267 [pool-27-thread-1] Error initializing process: 
java.io.IOException: Cannot run program "ffmpeg": error=2, Aucun fichier ou dossier de ce type
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047) ~[na:1.7.0_65]
        at net.pms.io.ProcessWrapperImpl.run(ProcessWrapperImpl.java:183) [pms.jar:1.90.1]
        at net.pms.io.ProcessWrapperImpl.runInSameThread(ProcessWrapperImpl.java:299) [pms.jar:1.90.1]
        at net.pms.dlna.DLNAMediaInfo.getFFmpegThumbnail(DLNAMediaInfo.java:473) [pms.jar:1.90.1]
        at net.pms.dlna.DLNAMediaInfo.parse(DLNAMediaInfo.java:770) [pms.jar:1.90.1]
        at net.pms.formats.Format.parse(Format.java:269) [pms.jar:1.90.1]
        at net.pms.dlna.RealFile.resolve(RealFile.java:191) [pms.jar:1.90.1]
        at net.pms.dlna.DLNAResource.run(DLNAResource.java:837) [pms.jar:1.90.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
Caused by: java.io.IOException: error=2, Aucun fichier ou dossier de ce type
        at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.7.0_65]
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:186) ~[na:1.7.0_65]
        at java.lang.ProcessImpl.start(ProcessImpl.java:130) ~[na:1.7.0_65]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028) ~[na:1.7.0_65]
        ... 10 common frames omitted
ERROR 2014-11-25 15:48:55.266 [pool-27-thread-4] Error initializing process: 
java.io.IOException: Cannot run program "ffmpeg": error=2, Aucun fichier ou dossier de ce type
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047) ~[na:1.7.0_65]
        at net.pms.io.ProcessWrapperImpl.run(ProcessWrapperImpl.java:183) [pms.jar:1.90.1]
        at net.pms.io.ProcessWrapperImpl.runInSameThread(ProcessWrapperImpl.java:299) [pms.jar:1.90.1]
        at net.pms.dlna.DLNAMediaInfo.getFFmpegThumbnail(DLNAMediaInfo.java:473) [pms.jar:1.90.1]
        at net.pms.dlna.DLNAMediaInfo.parse(DLNAMediaInfo.java:770) [pms.jar:1.90.1]
        at net.pms.formats.Format.parse(Format.java:269) [pms.jar:1.90.1]
        at net.pms.dlna.RealFile.resolve(RealFile.java:191) [pms.jar:1.90.1]
        at net.pms.dlna.DLNAResource.run(DLNAResource.java:837) [pms.jar:1.90.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
Caused by: java.io.IOException: error=2, Aucun fichier ou dossier de ce type
        at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.7.0_65]
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:186) ~[na:1.7.0_65]
        at java.lang.ProcessImpl.start(ProcessImpl.java:130) ~[na:1.7.0_65]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028) ~[na:1.7.0_65]
        ... 10 common frames omitted
```

And so on.

In Ubuntu 14.10, system on which those errors occured, ffmpeg is not provided anymore, but only avconv.
To solve this I only did that : 
    sudo ln -s /usr/bin/avconv /usr/bin/ffmpeg
But I think it would be useful to not have to do that.

**Comment by mine260309** [comment]
You can install ffmpeg on Ubuntu by adding a PPA, but you need to replace some packages after while.
See https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media for details.
