### ISSUE TITLE
Missing cuelib 1.2.1 - Maven 

### ISSUE THREAD

**Issue by clodbrasilino** [ps3mediaserver/ps3mediaserver#138]
As i tried to install, this error came up:

`$mvn com.savage7.maven.plugins:maven-external-dependency-plugin:resolve-external
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PS3 Media Server 1.90.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-external-dependency-plugin:0.5:resolve-external (default-cli) @ pms ---
[INFO] starting to resolve external dependencies
[INFO] attempting to resolve external artifact: jwbroek.cuelib:cuelib:1.2.1-2008-06-13:jar
Downloading: http://download.java.net/maven/2/jwbroek/cuelib/cuelib/1.2.1-2008-06-13/cuelib-1.2.1-2008-06-13.jar
Downloading: https://google-gson.googlecode.com/svn/mavenrepo/jwbroek/cuelib/cuelib/1.2.1-2008-06-13/cuelib-1.2.1-2008-06-13.jar
Downloading: https://repository.jboss.org/nexus/content/repositories/releases/jwbroek/cuelib/cuelib/1.2.1-2008-06-13/cuelib-1.2.1-2008-06-13.jar
Downloading: http://www.mygrid.org.uk/maven/repository/jwbroek/cuelib/cuelib/1.2.1-2008-06-13/cuelib-1.2.1-2008-06-13.jar
Downloading: https://nexus.codehaus.org/content/repositories/releases/jwbroek/cuelib/cuelib/1.2.1-2008-06-13/cuelib-1.2.1-2008-06-13.jar
Downloading: https://repo.maven.apache.org/maven2/jwbroek/cuelib/cuelib/1.2.1-2008-06-13/cuelib-1.2.1-2008-06-13.jar
[INFO] downloading artifact from URL: http://cuelib.googlecode.com/files/cuelib-1.2.1-2008-06-13.jar
[ERROR] 
java.io.FileNotFoundException: http://cuelib.googlecode.com/files/cuelib-1.2.1-2008-06-13.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1834)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
	at java.net.URL.openStream(URL.java:1038)
	at org.codehaus.plexus.util.io.URLInputStreamFacade.getInputStream(URLInputStreamFacade.java:77)
	at org.codehaus.plexus.util.FileUtils.copyStreamToFile(FileUtils.java:1057)
	at org.codehaus.plexus.util.FileUtils.copyURLToFile(FileUtils.java:1018)
	at com.savage7.maven.plugin.dependency.ResolveExternalDependencyMojo.execute(ResolveExternalDependencyMojo.java:155)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.563 s
[INFO] Finished at: 2017-02-11T09:50:07-03:00
[INFO] Final Memory: 8M/115M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.savage7.maven.plugins:maven-external-dependency-plugin:0.5:resolve-external (default-cli) on project pms: http://cuelib.googlecode.com/files/cuelib-1.2.1-2008-06-13.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

java.io.FileNotFoundException: http://cuelib.googlecode.com/files/cuelib-1.2.1-2008-06-13.jar

Doing some research, found out that the cuelib project seems to be not available anymore.

Any workarounds?

**Comment by Nadahar** [comment]
This project is abandoned, but [Universal Media Server](https://github.com/UniversalMediaServer/UniversalMediaServer) is a fork that's still alive. If you want to use PS3 Media Server despite the fact, [cuelib can still be downloaded here](storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/cuelib/cuelib-1.2.1-2008-06-13.jar).
